config/routes.rb
Rails.application.routes.draw do
  
  resources :posts

  root 'static_pages#welcome'

  get '/about', to: 'static_pages#about', as: :about

  get '/contact', to: 'static_pages#contact', as: :contact

end

app/models/post.rb
class Post < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
        redirect_to posts_path
    else
        render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(post_params)
        redirect_to posts_path
    else
        render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

private

def post_params
    params.require(:post).permit(:title, :author, :body)
end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def welcome
    @posts = Post.order(created_at: :desc).limit(2)
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<div id="Nav">
  <h1>Alex Burton</h1>
  <h4>Web Developer</h4>

  <%= link_to 'Home', root_path, :class => "nav_link" %>
  <%= link_to 'About', about_path, :class=>"nav_link" %>
  <%= link_to 'Contact', contact_path, :class=>"nav_link" %>
  <%= link_to 'Blog', posts_path, :class => "nav_link" %> 

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
    
  <div id="content_div">
    <%= yield %>
  </div>
</body>
<footer>
   <%= image_tag("facebook-wrap.png", :alt=> "Facebook" ) %>
   <%= image_tag("twitter-wrap.png", :alt=> "Twitter" ) %>
</footer>
</html>

app/views/posts/edit.html.erb
<h1> Edit Post </h1>
<%= form_for @post do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>
<br>
<br>
  <%= f.label :body %>
  <%= f.text_area :body, :rows => 20 %>

  <%= f.submit %>
  <%= button_to 'Cancel', posts_path %>
<% end %>

<footer>
 <p>&copy; 2014 Alex Burton.</p>
</footer>

app/views/posts/index.html.erb
<!-- <h1 class="Post_"> Posts </h1> -->
<% @posts.each do |post| %>
    <div class="post_content">
      <h2 class="post_title"><%= post.title %></h2>
      <h3 class="post_author"><%= post.author %></h2>
      <p><%= truncate(post.body, length: 400) %></p>
        <%= link_to 'Show', post_path(post.id) %>
        <%= link_to 'Edit', edit_post_path(post.id) %>
      <%= link_to 'delete', post, method: :delete %>
    </div>
<% end %>

<p><%= link_to 'New Post', new_post_path %></p>

<footer>
 <p>&copy; 2014 Alex Burton.</p>
</footer>

app/views/posts/new.html.erb
<h1> New Post </h1>
<%= form_for @post do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>
<br>
<br>
  <%= f.label :body %>
  <%= f.text_area :body, :rows => 20 %>

  <%= f.submit %>
  <%= button_to 'Cancel', posts_path %>
<% end %>

<footer>
 <p>&copy; 2014 Alex Burton.</p>
</footer>

app/views/posts/show.html.erb
<h1> Post </h1>
<h2><%= @post.title  %></h2>
<h3><%= @post.author %></h2>
<p><%= @post.body %></p>
<%= link_to 'Back', posts_path %>

<footer>
 <p>&copy; 2014 Alex Burton.</p>
</footer>

app/views/static_pages/about.html.erb
<head>
<title>Alex Burton | Web Developer</title>   
</head>

<p>My name is Alex and I'm 20 years old I graduated high school in 2012 and tried 
	one year of college, I didnt enjoy traditional schooling. I'm just starting web 
	development for the first time. I have always been into tech. I started off 
	rooting phones and editing roms. And now I'm here at DevPointLabs learning
	a whole new language. </p>

<h3>Fun things I do</h3>
<li>Drumming</li>
<li>Video games</li>	
<li>Android customization</li>
<li>Web development</li>

<h3>More about me</h3>
<p>I'm a drummer and my drumming carrer has taken me to march with 
	Riverside City College also known to be "Hollywood's Band". In the year 2012 I did
	a music video with Travis Barker and Yellow Wolf and a commercial for the game 
	Just Dance 4. That gave me the chance to participate in the Pasadena Rose parade
	of 2013. The following new years I traveled with the band to London and Madrid to 
	march in the London New Years parade and Madrids Cabalgata de Reyes parade.</p>

<footer>
  	<p>&copy; 2014 Alex Burton.</p>
</footer>

app/views/static_pages/contact.html.erb
<head>
<title>Alex Burton | Web Developer</title>   
</head>

<body>
  <h3>Contact Details</h3>
    <h4>If you would like to contact me please email me or tweet me</h4>
      <p>Email</p>
      <li><a href="mailto:alex.burton1993@gmail.com">alex.burton1993@gmail.com</a></li>
      <p>Twitter</p>
      <li><a href="http://twitter.com/intent/tweet?screen_name=Alexand3rsc0tt">@Alexand3rsc0tt</a></li>
    
         
  <footer>
  	<p>&copy; 2014 Alex Burton.</p>
  </footer>
</body>

app/views/static_pages/welcome.html.erb
<h1>Welcome!</h1>

<% @posts.each do |post| %>
  <div class= "post_content">
    <h2 class="post_title"><%= post.title %></h2>
    <h3 class="post_author"><%= post.author %></h2>
      <p><%= truncate(post.body, length: 400) %></p>
      <%= link_to 'Show post', post_path(post.id) %>
  </div>
<% end %>

<footer>
 <p>&copy; 2014 Alex Burton.</p>
</footer>